"""Test script for YAML generation workflow."""

import requests
import json
from datetime import datetime

BASE_URL = "http://127.0.0.1:8001/api"

# Sample Pick Basic code
SAMPLE_CODE = """* INVOICE REPORT PROGRAM
* Generates daily invoice summary

PROGRAM INVOICE.REPORT

* Open files
OPEN 'INVOICE' TO INVOICE.FILE ELSE STOP "Cannot open INVOICE file"
OPEN 'CUSTOMER' TO CUSTOMER.FILE ELSE STOP "Cannot open CUSTOMER file"

* Initialize variables
TOTAL.AMOUNT = 0
INVOICE.COUNT = 0
TODAY = DATE()

* Generate report header
PRINT "Daily Invoice Report - ":OCONV(TODAY, "D2/")
PRINT STRING('-', 60)

* Read and process invoices
SELECT INVOICE.FILE
LOOP
    READNEXT INVOICE.ID ELSE EXIT
    READ INVOICE.REC FROM INVOICE.FILE, INVOICE.ID THEN
        * Get customer info
        CUST.ID = INVOICE.REC<1>
        READ CUST.REC FROM CUSTOMER.FILE, CUST.ID THEN
            CUST.NAME = CUST.REC<1>
        END ELSE
            CUST.NAME = "Unknown"
        END
        
        * Calculate invoice total
        INV.AMOUNT = INVOICE.REC<5>
        TOTAL.AMOUNT = TOTAL.AMOUNT + INV.AMOUNT
        INVOICE.COUNT = INVOICE.COUNT + 1
        
        * Print invoice line
        PRINT INVOICE.ID "L#10":CUST.NAME "L#30":INV.AMOUNT "R#10"
    END
REPEAT

* Print summary
PRINT STRING('-', 60)
PRINT "Total Invoices: ":INVOICE.COUNT
PRINT "Total Amount: ":OCONV(TOTAL.AMOUNT, "MD2,$")
PRINT ""

STOP
END
"""


def test_yaml_workflow():
    """Test the complete YAML generation workflow."""
    
    print("=" * 80)
    print("YAML GENERATION WORKFLOW TEST")
    print("=" * 80)
    print()
    
    # Step 1: Create a new migration job
    print("📝 Step 1: Creating migration job...")
    job_data = {
        "original_source_code": SAMPLE_CODE,
        "target_language": "PYTHON",
        "created_by": "test_user",
        "job_name": "Invoice Report Migration",
        "description": "Daily invoice reporting program",
        "source_filename": "INVOICE.REPORT.bp"
    }
    
    response = requests.post(f"{BASE_URL}/jobs/", json=job_data)
    
    if response.status_code != 201:
        print(f"❌ Failed to create job: {response.status_code}")
        print(response.text)
        return
    
    job = response.json()
    job_id = job["id"]
    print(f"✅ Job created successfully: ID = {job_id}")
    print(f"   State: {job['current_state']}")
    print()
    
    # Step 2: Generate YAML
    print("🤖 Step 2: Generating YAML with LLM...")
    yaml_gen_data = {
        "performed_by": "test_user",
        "force_regenerate": False
    }
    
    response = requests.post(
        f"{BASE_URL}/jobs/{job_id}/yaml/generate",
        json=yaml_gen_data
    )
    
    if response.status_code != 201:
        print(f"❌ Failed to generate YAML: {response.status_code}")
        print(response.text)
        return
    
    yaml_version = response.json()
    print(f"✅ YAML generated: Version {yaml_version['version_number']}")
    print(f"   Valid: {yaml_version['is_valid']}")
    print(f"   Generated by: {yaml_version['generated_by']}")
    
    if not yaml_version['is_valid']:
        print(f"   ⚠️  Validation errors: {len(yaml_version['validation_errors'])} errors")
        for i, error in enumerate(yaml_version['validation_errors'][:5], 1):  # Show first 5
            print(f"      {i}. {error}")
    else:
        print(f"   ✓ YAML is valid!")
    
    print()
    
    # Step 3: View YAML content (first 500 chars)
    print("📄 Step 3: YAML Content Preview:")
    print("-" * 80)
    yaml_content = yaml_version['yaml_content']
    print(yaml_content[:500])
    if len(yaml_content) > 500:
        print(f"\n... [truncated {len(yaml_content) - 500} characters]")
    print("-" * 80)
    print()
    
    # Step 4: Get YAML statistics
    print("📊 Step 4: YAML Statistics:")
    response = requests.get(f"{BASE_URL}/jobs/{job_id}/yaml/statistics")
    
    if response.status_code == 200:
        stats = response.json()
        print(f"   Total versions: {stats['total_versions']}")
        print(f"   Valid versions: {stats['valid_versions']}")
        print(f"   Invalid versions: {stats['invalid_versions']}")
        print(f"   Approved versions: {stats['approved_versions']}")
    print()
    
    # Step 5: List all YAML versions
    print("📋 Step 5: All YAML Versions:")
    response = requests.get(
        f"{BASE_URL}/jobs/{job_id}/yaml/versions",
        params={"include_invalid": True}
    )
    
    if response.status_code == 200:
        versions = response.json()
        for v in versions:
            status = "✓ Valid" if v['is_valid'] else "✗ Invalid"
            approved = " [APPROVED]" if v['is_approved'] else ""
            print(f"   Version {v['version_number']}: {status}{approved}")
            if v['has_errors']:
                print(f"      Errors: {v['error_count']}")
    print()
    
    # Step 6: Get job details to verify state transition
    print("🔍 Step 6: Job State After YAML Generation:")
    response = requests.get(f"{BASE_URL}/jobs/{job_id}")
    
    if response.status_code == 200:
        job = response.json()
        print(f"   Current state: {job['current_state']}")
        print(f"   Created: {job['created_at']}")
        print(f"   Updated: {job['updated_at']}")
    print()
    
    # Step 7: Check if we can approve the YAML (if valid)
    if yaml_version['is_valid']:
        print("✅ Step 7: Approving YAML version...")
        approval_data = {
            "approved_by": "test_reviewer",
            "comments": "YAML structure looks good, approved for code generation"
        }
        
        response = requests.post(
            f"{BASE_URL}/jobs/{job_id}/yaml/versions/{yaml_version['version_number']}/approve",
            json=approval_data
        )
        
        if response.status_code == 200:
            approved_version = response.json()
            print(f"   ✓ YAML version approved by {approved_version['approved_by']}")
            print(f"   Comments: {approved_version['approval_comments']}")
        else:
            print(f"   ⚠️  Approval failed: {response.status_code}")
    else:
        print("⏭️  Step 7: Skipped (YAML invalid, cannot approve)")
    
    print()
    print("=" * 80)
    print("TEST COMPLETED")
    print("=" * 80)


if __name__ == "__main__":
    try:
        test_yaml_workflow()
    except requests.exceptions.ConnectionError:
        print("❌ ERROR: Cannot connect to server at http://127.0.0.1:8001")
        print("   Make sure the server is running!")
    except Exception as e:
        print(f"❌ ERROR: {type(e).__name__}: {str(e)}")
        import traceback
        traceback.print_exc()
