export { default as VSCodeLayout } from './VSCodeLayout';
export type { VSCodeLayoutProps } from './VSCodeLayout';
export { default as ActivityBar } from './ActivityBar';
export type { ActivityBarTab } from './ActivityBar';
export { default as TitleBar }    from './TitleBar';
export { default as StatusBar }   from './StatusBar';
export { default as ResizeHandle } from './ResizeHandle';
export { default as ExplorerPanel } from './ExplorerPanel';
export type { ExplorerPanelProps } from './ExplorerPanel';
export { default as EditorPanel } from './EditorPanel';
export type { EditorPanelProps } from './EditorPanel';
export { default as DirectEditorPanel } from './DirectEditorPanel';
export type { DirectEditorPanelProps } from './DirectEditorPanel';
export { default as ChatPanel } from './ChatPanel';
export type { ChatPanelProps } from './ChatPanel';
export { VS } from './vscodeTheme';
