"""
YAML Structure Schema - The STRICT CONTRACT for LLM output.
This defines the exact structure that YAML Generator (Agent 1) must produce.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Any, Dict
from datetime import datetime
from enum import Enum


# Enums for YAML structure

class ProgramType(str, Enum):
    """Type of Pick Basic program."""
    PROGRAM = "PROGRAM"
    SUBROUTINE = "SUBROUTINE"
    FUNCTION = "FUNCTION"
    MENU = "MENU"


class VariableScope(str, Enum):
    """Variable scope types."""
    LOCAL = "LOCAL"
    GLOBAL = "GLOBAL"
    COMMON = "COMMON"
    PARAMETER = "PARAMETER"


class LogicNodeType(str, Enum):
    """Types of logic flow nodes."""
    LOOP = "LOOP"
    CONDITIONAL = "CONDITIONAL"
    FILE_IO = "FILE_IO"
    SUBROUTINE_CALL = "SUBROUTINE_CALL"
    ASSIGNMENT = "ASSIGNMENT"
    EXPRESSION = "EXPRESSION"
    RETURN = "RETURN"
    GOTO = "GOTO"
    CASE = "CASE"
    PRINT = "PRINT"
    INPUT = "INPUT"


class FileOperationType(str, Enum):
    """Pick Basic file operation types."""
    READ = "READ"
    WRITE = "WRITE"
    DELETE = "DELETE"
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    READNEXT = "READNEXT"
    READU = "READU"
    WRITEV = "WRITEV"
    SELECT = "SELECT"


# Schema Components

class YAMLMetadata(BaseModel):
    """Metadata section of the YAML."""
    original_filename: Optional[str] = Field(None, description="Source file name")
    analysis_timestamp: str = Field(..., description="When analysis was performed")
    pick_basic_version: Optional[str] = Field(None, description="Pick Basic version/flavor")
    total_lines: Optional[int] = Field(None, description="Total lines in source")
    complexity_estimate: Optional[str] = Field(None, description="Low, Medium, High")


class ProgramStructure(BaseModel):
    """Overall program structure."""
    type: ProgramType = Field(..., description="Program type")
    name: Optional[str] = Field(None, description="Program/subroutine name")
    entry_points: List[str] = Field(default_factory=list, description="Entry point labels")
    exit_points: List[str] = Field(default_factory=list, description="Exit/return points")


class VariableDeclaration(BaseModel):
    """Variable declaration information."""
    name: str = Field(..., description="Variable name")
    type: Optional[str] = Field(None, description="Inferred type (string, numeric, array, etc.)")
    scope: VariableScope = Field(..., description="Variable scope")
    initial_value: Optional[str] = Field(None, description="Initial value if any")
    description: Optional[str] = Field(None, description="Purpose of the variable")
    multi_value: bool = Field(False, description="Is this a multi-value field")


class LogicFlowNode(BaseModel):
    """Recursive node representing program logic."""
    section_id: str = Field(..., description="Unique identifier for this node")
    type: LogicNodeType = Field(..., description="Node type")
    original_code: str = Field(..., description="Original Pick Basic code")
    semantic_intent: str = Field(..., description="What this code does in plain English")
    line_numbers: Optional[str] = Field(None, description="Source line numbers")
    
    # Optional fields depending on type
    condition: Optional[str] = Field(None, description="Condition expression (for conditionals/loops)")
    loop_variable: Optional[str] = Field(None, description="Loop control variable")
    target_label: Optional[str] = Field(None, description="Target for GOTO/GOSUB")
    
    # Recursive children
    children: List["LogicFlowNode"] = Field(default_factory=list, description="Nested logic blocks")


class FileOperation(BaseModel):
    """File I/O operation details."""
    operation: FileOperationType = Field(..., description="Type of file operation")
    file_handle: str = Field(..., description="File variable name")
    record_id: Optional[str] = Field(None, description="Record ID variable")
    field_number: Optional[str] = Field(None, description="Field/attribute number")
    original_statement: str = Field(..., description="Original Pick Basic statement")
    semantic_intent: str = Field(..., description="What this operation does")
    line_number: Optional[int] = Field(None, description="Source line number")


class SubroutineInfo(BaseModel):
    """Called subroutine information."""
    name: str = Field(..., description="Subroutine name")
    parameters: List[str] = Field(default_factory=list, description="Parameter names")
    is_external: bool = Field(False, description="Is this an external/library subroutine")
    purpose: Optional[str] = Field(None, description="What the subroutine does")


# Main YAML Structure

class PickBasicYAMLSchema(BaseModel):
    """
    The complete YAML structure that must be generated by LLM Agent 1.
    This is the STRICT contract - validation must enforce this.
    """
    metadata: YAMLMetadata = Field(..., description="Program metadata")
    program_structure: ProgramStructure = Field(..., description="Overall structure")
    variables: List[VariableDeclaration] = Field(default_factory=list, description="All variables")
    logic_flow: List[LogicFlowNode] = Field(..., description="Program logic as AST")
    file_operations: List[FileOperation] = Field(default_factory=list, description="All file I/O")
    subroutines: List[SubroutineInfo] = Field(default_factory=list, description="Called subroutines")
    
    # Optional sections
    labels: Optional[Dict[str, str]] = Field(None, description="Label mappings")
    comments: Optional[List[str]] = Field(None, description="Important comments from source")
    warnings: Optional[List[str]] = Field(None, description="Analysis warnings")


# Response schemas for YAML endpoints

class YAMLVersionResponse(BaseModel):
    """Response schema for YAML version."""
    id: int
    job_id: int
    version_number: int
    parent_version_id: Optional[int]
    yaml_content: str
    is_valid: bool
    is_approved: bool
    validation_errors: Optional[str]
    generated_at: datetime
    llm_model_used: Optional[str]
    
    model_config = {"from_attributes": True}


class YAMLVersionSummary(BaseModel):
    """Condensed YAML version summary."""
    id: int
    version_number: int
    is_valid: bool
    is_approved: bool
    generated_at: datetime
    
    model_config = {"from_attributes": True}


class YAMLGenerationRequest(BaseModel):
    """Request to generate YAML for a job."""
    job_id: int = Field(..., description="Job to generate YAML for")
    regenerate: bool = Field(False, description="Is this a regeneration")
    context_from_review: Optional[str] = Field(None, description="Review comments to consider")


# Enable forward references for recursive LogicFlowNode
LogicFlowNode.model_rebuild()
